import type { Metadata } from "next";
import "./globals.css";
import NavBar from "./_components/navigation/NavBar";

export const metadata: Metadata = {
  title: "My Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <NavBar />
        <main className="p-6">{children}</main>
      </body>
    </html>
  );
}
